-- Conversion of mds to pdf (planning to, but)
-- I don't have pandoc rn, so 
-- vim.api.nvim_create_user_command("Pandoc", function(args)
-- 	vim.cmd(
-- 		"!pandoc -i "
-- 			.. vim.fn.fnameescape(vim.fn.expand("%"))
-- 			.. " -o "
-- 			.. vim.fn.fnameescape(vim.fn.expand("%:r"))
-- 			.. "."
-- 			.. args.args
-- 	)
-- end, {
-- 	nargs = 1,
-- })
