#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # don't put these under quotes, the ~ must be expanded by bash-shell before execution
    DIRS=(
        ~/Videos/
        ~/Pictures/
        ~/Documents/
    )
    selected=$(find -L ${DIRS[@]} -type f -printf "%f\n" | rofi -dmenu -i -p " :")
    full_path=$(find -L ${DIRS[@]} -type f -name "$selected")
    echo "$full_path"
fi

if [[ -z $selected ]]; then
    echo "No media selected"
    exit 0
fi


# you can change defaults with xdg-mime
xdg-open "$full_path"&
clear
