#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # don't put these under quotes, the ~ must be expanded by bash-shell before execution
    DIRS=(
        ~/repos/collage/notes
        ~/Sync/notes/_assets/
    )
    selected=$(find ${DIRS[@]} -type f -printf "%f\n" | grep ".pdf" | rofi -dmenu -i -p " Note:")
    full_path=$(find ${DIRS[@]} -type f -name "$selected")
    echo "$full_path"
fi

if [[ -z $selected ]]; then
    echo "No note selected"
    exit 0
fi


zathura "$full_path"&
clear
