#!/usr/bin/env bash

STATEFILE="/tmp/pomo_state"
NOTIFY_SOUND="$HOME/Music/noti_sound"

play_notification() {
    if [[ -f "$NOTIFY_SOUND" ]]; then 
        if command -v mpv &>/dev/null; then
            mpv --really-quiet "$NOTIFY_SOUND" &
        fi
    fi
}

function start() {
    if [[ -f $STATEFILE ]]; then
        notify-send "Pomodoro already running, ask for extra when you complete!"
        status
        exit 0
    fi

    # for checking status
    work_min=50
    work_sec=$((work_min * 60))
    echo "$(( $(date +%s) + work_sec )) work" > "$STATEFILE"

    notify-send "Pomodoro started for $work_min minutes."

    echo "$work_sec"
    sleep "$work_sec" && \
        notify-send "Pomodoro complete"
    play_notification&

    # cleanup
    rm -f "$STATEFILE"
}

function extra_pomo() {
    if [[ -f $STATEFILE ]]; then
        notify-send "Pomodoro already running, ask for extra when you complete!"
        status
        exit 0
    fi

    # for checking status
    work_min=25
    work_sec=$((work_min * 60))

    echo "$(( $(date +%s) + work_sec )) work" > "$STATEFILE"

    notify-send "Extra pomodoro started for $work_min minutes."
    
    sleep "$work_sec" &&\
        notify-send "Extra pomodoro complete"
    play_notification&

    # cleanup
    rm -f "$STATEFILE"
}

function break() {
    if [[ -f $STATEFILE ]]; then
        notify-send "Pomodoro already running, ask for extra when you complete!"
        status
        exit 0
    fi

    # for checking status
    break_min=10
    break_sec=$((break_min * 60))
    echo "$(( $(date +%s) + break_sec )) break" > "$STATEFILE"

    notify-send "Break started for $break_min minutes."

    sleep "$break_sec" && notify-send "Break Complete"
    play_notification&

    # cleanup
    rm -f "$STATEFILE"
}

function status() {
    if [[ -f "$STATEFILE" ]]; then
        read end type < "$STATEFILE"
        now=$(date +%s)
        rem=$(( end - now ))

        if (( rem > 0 )); then
            if [[ "$type" == "work" ]]; then
                notify-send "Pomodoro running" \
                    "$(printf 'Time remaining: %d minutes %d seconds' $((rem / 60)) $((rem % 60)))"
            else
                notify-send "Break running" \
                    "$(printf 'Time remaining: %d minutes %d seconds' $((rem / 60)) $((rem % 60)))"
            fi
            exit 0
        else
            # Session expired, notify and do not remove state file here
            rm -rf "$STATEFILE"
        fi
    else
        notify-send "No tasks runnig."
    fi
}

question="$1"
case "$question" in
    "start")
        start
        ;;
    "break")
        break
        ;;
    "status")
        status
        ;;
    "extra")
        extra_pomo
        ;;
    *)
        notify-send "Wrong argument"
        ;;
esac
