#!/bin/bash

# not immune to errors
# very simple, with ffmpeg code copied 
# from https://releasecandidate.dev/posts/2023/how-to-record-your-screen-from-bash-on-linux-arch/

USAGE="Usage: record-screen [-l | -ll] [OUTPUT_FILE_PATH] \n-l = lossy \n-ll = lossless"

if [[ $# -eq 1 ]]; then
    # lossy
    ffmpeg -f x11grab -video_size $(xdpyinfo | grep 'dimensions:' | awk '{print $2;}') -i :0.0 -c:v libx264 -preset ultrafast $1
else 
    if [[ $# -eq 2 ]]; then
        if [[ $1 -eq "-l" ]]; then
            ffmpeg -f x11grab -video_size $(xdpyinfo | grep 'dimensions:' | awk '{print $2;}') -i :0.0 -c:v libx264 -preset ultrafast $2
        else 
            if [[ $1 -eq "-ll" ]]; then
                ffmpeg -f x11grab -video_size $(xdpyinfo | grep 'dimensions:' | awk '{print $2;}') -i :0.0 -c:v ffv1 -level 3 -g 1 -coder 1 -context 0 $2
            else 
                echo $USAGE
            fi
        fi
    else
        echo $USAGE
    fi
fi
