#!/usr/bin/env bash

# if directory is provided as argument, use that
if [[ $# -eq 1 ]]; then
    selected=$1
else
    # select the directory using fuzzy finder

    # don't put these under quotes, the ~ must be expanded by bash-shell before execution
    DIRS=(
        # ~/projects
        # ~/tests 
        ~/repos
        ~/repos/srj-17
        ~/repos/ranhoodlum
        ~/Sync/notes
    )
    selected=$(find ${DIRS[@]} -mindepth 1 -maxdepth 1 -type d | fzf)
fi

# exit early
if [[ -z $selected ]]; then
    exit 0
fi

# tr = translate . to _
selected_name=$(basename "$selected" | tr . _)

# if we don't have a session with the selected_name
if ! tmux has-session -t=$selected_name 2> /dev/null; then

    # create a detached session
    tmux new-session -ds "$selected_name" -c $selected

    # create windows without attaching
    WINDOWS=("term" "ls" "db")

    for window in "${WINDOWS[@]}"; do
        tmux new-window -t "$selected_name" -n "$window"
    done

    # Switch to the first window 
    tmux select-window -t "$selected_name:1"

fi

# TMUX is only set when we're inside the client
if [[ -z $TMUX ]]; then
    tmux attach -t "$selected_name"
else
    tmux switch-client -t $selected_name
fi
