# Initial setup
set -g status-keys vi


# DON'T SET THIS IF NOT USING ALACRITTY TERMINAL
# set-option -ga terminal-features ",alacritty*:RGB"
set -g default-terminal "screen-256color"


## source the configuration files from .bashrc
## tmux by default runs a login shell, so it doesn't source from .bashrc
## for this, i've added source ~/.bashrc in my profile
## https://unix.stackexchange.com/a/320496/628695


# new prefix key in town
set-option -g prefix C-a


## advice from neovim checkhealth
set-option -a terminal-features 'xterm-256color:RGB'
set-option -a terminal-overrides 'xterm-256color:Tc'
set-option -g focus-events on



bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R


# Set easier window split keys (try to use defaults)
# bind-key V split-window -h 
# bind-key S split-window -v


# Synchronize panes
bind-key y set-window-option synchronize-panes\; display-message "synchronize mode toggled."


# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."


# Key bindings for copy-paste
setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection     # Begin selection in copy mode.
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle  # Begin selection in copy mode.
# bind-key -T copy-mode-vi 'y' send -X copy-selection      # Yank selection in copy mode.
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"


# Mouse Mode
set -g mouse on


# Lengthen the amount of time status messages are displayed
set-option -g display-time 3000
set-option -g display-panes-time 3000


# Set the base-index to 1 rather than 0
set -g base-index 1
set-window-option -g pane-base-index 1


# Automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on


# Allow the arrow key to be used immediately after changing windows.
set-option -g repeat-time 0


# No delay for escape key press
set -sg escape-time 0


# Change background color of a tab when activity occurs
setw -g monitor-activity on


# Do NOT reset the color of the tab after activity stops occuring
setw -g monitor-silence 0


# Disable bell
setw -g monitor-bell off


# Disable visual text box when activity occurs
set -g visual-activity off

# theme
set-window-option -g window-status-style fg=colour245
set-window-option -g window-status-current-style bold,fg=colour249
set-option -g pane-border-style fg=colour245
set-option -g pane-active-border-style fg=colour248
# set -g window-status-activity-style bold,bg=colour234,fg=white
# set-option -g message-style bg=colour237,fg=colour231

# status bar
set -g status-justify centre
set -g status-bg color236
set -g status-fg colour35
set -g status-interval 60
set -g status-left-length 50
set -g status-left "#[fg=colour249,bold] #H #[fg=colour249] [#S] $tmux_target_lower"
set -g status-right "#[fg=colour249,bold] #[fg=colour249] %H:%M "
# set -g status-style 'bg=#333333 fg=#5eacd3'

bind-key -r f run-shell "tmux neww ~/myscripts/tmux-sessionizer"
bind-key -r o run-shell "tmux neww ~/myscripts/tmux-windownizer"

# set this up to go directly to your desired project
# you can set more than 1 of these bindings
# bind-key -r t run-shell "~/myScripts/tmux-sessionizer ~/repos/srj-17/your-project/"
